"""DB repo package facade — the single import surface for the data layer.

Re-exports the full live attribute set (the public API plus get_connection,
_conn_ctx, _nulltx, _TERMINAL_STATUSES, _ACCENT_CLASS_MAP, _pad_references,
_scrub), so callers say `from app.db import repo` and never reach into an
aggregate module directly.

SEAM CAVEAT (tests depend on this being accurate): patching an attribute on this
facade — `monkeypatch.setattr(repo, "fn", ...)` — rebinds only the facade's own
name. It does NOT intercept a call made from one aggregate module to another name
in that SAME module: record_run_error's internal calls to set_status/_scrub, for
example, resolve against runs.py's module globals, which the facade patch never
touched. To stub those, patch app.db.repo.runs directly. See tests/test_gateway.py
and tests/test_persistence.py, which rely on exactly this distinction.
"""

from app.db.repo._shared import _conn_ctx, _nulltx
from app.db.repo.demo import (
    bind_demo_business,
    get_demo_binding,
    get_record_only_flag,
    list_businesses,
    load_all_runs,
    load_line_items,
    set_record_only,
)
from app.db.repo.emails import (
    _HEADER_MATCH_PREDICATE,
    _pad_references,
    find_any_run_for_header,
    find_awaiting_reply_for_header,
    find_stranded_unconsumed_replies,
    get_inbound_by_message_id,
    get_outbound_for_round,
    get_outbound_message_id,
    get_outbound_references_chain,
    insert_email_message,
    load_consumed_replies,
    load_outbound_emails,
    load_thread_messages,
    mark_reply_consumed,
    update_email_message_sent,
    update_email_message_state,
)
from app.db.repo.jobs import (
    claim_job,
    complete_job,
    enqueue_job,
    fail_job,
    get_job,
    release_leases,
)
from app.db.repo.pipeline_state import (
    clear_reply_context,
    get_clarification_round,
    load_clarified_fields,
    load_pre_clarify_extracted,
    persist_decision,
    persist_extracted,
    persist_reconciliation,
    replace_line_items,
    rewind_for_reclaim,
    set_alias_candidates,
    set_clarification_round,
    set_clarified_fields,
    set_hours_changes,
    set_pre_clarify_extracted,
    update_known_alias,
)
from app.db.repo.roster import load_roster_for_business
from app.db.repo.runs import (
    _ACCENT_CLASS_MAP,
    _TERMINAL_STATUSES,
    RUN_COLS,
    _scrub,
    claim_status,
    create_run,
    find_business_by_sender,
    find_run_by_message_id,
    insert_inbound_email,
    link_email_to_run,
    load_business_name,
    load_inbound_email,
    load_run,
    load_source_email,
    record_run_error,
    set_status,
    sweep_stranded_runs,
)
from app.db.supabase import get_connection

__all__ = [
    "get_connection",
    "_conn_ctx",
    "_nulltx",
    "bind_demo_business",
    "get_demo_binding",
    "list_businesses",
    "load_all_runs",
    "load_line_items",
    "set_record_only",
    "get_record_only_flag",
    "_HEADER_MATCH_PREDICATE",
    "_pad_references",
    "find_any_run_for_header",
    "find_awaiting_reply_for_header",
    "find_stranded_unconsumed_replies",
    "get_inbound_by_message_id",
    "get_outbound_for_round",
    "get_outbound_message_id",
    "get_outbound_references_chain",
    "insert_email_message",
    "load_consumed_replies",
    "load_outbound_emails",
    "load_thread_messages",
    "mark_reply_consumed",
    "update_email_message_sent",
    "update_email_message_state",
    "clear_reply_context",
    "get_clarification_round",
    "load_clarified_fields",
    "load_pre_clarify_extracted",
    "persist_decision",
    "persist_extracted",
    "persist_reconciliation",
    "replace_line_items",
    "set_alias_candidates",
    "set_clarification_round",
    "set_clarified_fields",
    "set_hours_changes",
    "set_pre_clarify_extracted",
    "update_known_alias",
    "rewind_for_reclaim",
    "claim_job",
    "complete_job",
    "enqueue_job",
    "fail_job",
    "get_job",
    "release_leases",
    "load_roster_for_business",
    "_ACCENT_CLASS_MAP",
    "_TERMINAL_STATUSES",
    "RUN_COLS",
    "_scrub",
    "claim_status",
    "create_run",
    "find_business_by_sender",
    "find_run_by_message_id",
    "insert_inbound_email",
    "link_email_to_run",
    "load_business_name",
    "load_inbound_email",
    "load_run",
    "load_source_email",
    "record_run_error",
    "set_status",
    "sweep_stranded_runs",
]
