"""DB repo package facade — the single import surface for the data layer.

Re-exports the full live attribute set (the public API plus get_connection,
_conn_ctx, _nulltx, _TERMINAL_STATUSES, _ACCENT_CLASS_MAP, _pad_references,
_scrub), so callers say `from app.db import repo` and never reach into an
aggregate module directly.

SEAM CAVEAT (tests depend on this being accurate): patching an attribute on this
facade — `monkeypatch.setattr(repo, "fn", ...)` — rebinds only the facade's own
name. It does NOT intercept a call made from one aggregate module to another name
in that SAME module: record_run_error's internal calls to set_status/_scrub, for
example, resolve against runs.py's module globals, which the facade patch never
touched. To stub those, patch app.db.repo.runs directly. See tests/test_gateway.py
and tests/test_persistence.py, which rely on exactly this distinction.
"""

from app.db.repo._shared import _conn_ctx, _nulltx
from app.db.repo.demo import (
    bind_demo_business,
    get_demo_binding,
    get_record_only_flag,
    list_businesses,
    load_all_runs,
    load_line_items,
    load_prior_reconciled_paystub_totals,
    set_record_only,
)
from app.db.repo.emails import (
    _HEADER_MATCH_PREDICATE,
    _pad_references,
    find_any_run_for_header,
    find_awaiting_reply_for_header,
    get_inbound_by_message_id,
    get_inbound_email_by_id,
    get_outbound_for_round,
    get_outbound_message_id,
    get_outbound_references_chain,
    get_unconfirmed_outbound,
    insert_email_message,
    load_consumed_replies,
    load_delivery_review_snapshot,
    load_outbound_emails,
    load_outbound_snapshot,
    load_snapshot_attachment,
    load_thread_messages,
    mark_reply_consumed,
    reserve_outbound_snapshot,
    update_email_message_sent,
    update_email_message_state,
)
from app.db.repo.inbound_events import (
    insert_or_get_inbound_event,
    load_inbound_event,
    purge_terminal_inbound_events,
)
from app.db.repo.job_settlement import (
    SettlementOutcome,
    enqueue_classified_retry,
    enqueue_operator_resume_retry,
    reap_expired_final_attempt,
    settle_background_terminal,
    settle_infrastructure_failure,
    settle_outbound_delivery_job,
    settle_pipeline_job,
)
from app.db.repo.jobs import (
    AdvanceSendJobOutcome,
    advance_existing_clarification_delivery_review_job_due_now,
    advance_existing_send_job_due_now,
    claim_job,
    complete_job,
    count_open_jobs,
    enqueue_job,
    fail_job,
    get_job,
    get_run_queue_label,
    release_leases,
    send_outbound_dedup_key,
)
from app.db.repo.operator_resume_resolutions import (
    OperatorResolutionSubmission,
    commit_operator_resume_resolution,
    create_operator_resume_resolution,
    load_operator_resume_resolution,
    operator_resume_dedup_key,
    prepare_authoritative_operator_resume,
)
from app.db.repo.pipeline_state import (
    clear_reply_context,
    get_clarification_round,
    load_clarified_fields,
    load_pre_clarify_extracted,
    persist_decision,
    persist_extracted,
    persist_reconciliation,
    replace_line_items,
    rewind_for_reclaim,
    set_alias_candidates,
    set_clarification_round,
    set_clarified_fields,
    set_hours_changes,
    set_pre_clarify_extracted,
    update_known_alias,
)
from app.db.repo.roster import load_roster_for_business
from app.db.repo.runs import (
    _ACCENT_CLASS_MAP,
    _TERMINAL_STATUSES,
    RUN_COLS,
    _scrub,
    claim_status,
    create_run,
    find_business_by_sender,
    find_run_by_message_id,
    insert_inbound_email,
    link_email_to_run,
    load_business_name,
    load_inbound_email,
    load_run,
    load_source_email,
    record_run_error,
    set_status,
)
from app.db.supabase import get_connection

__all__ = [
    "get_connection",
    "_conn_ctx",
    "_nulltx",
    "bind_demo_business",
    "get_demo_binding",
    "list_businesses",
    "load_all_runs",
    "load_line_items",
    "load_prior_reconciled_paystub_totals",
    "set_record_only",
    "get_record_only_flag",
    "_HEADER_MATCH_PREDICATE",
    "_pad_references",
    "find_any_run_for_header",
    "find_awaiting_reply_for_header",
    "get_inbound_email_by_id",
    "get_inbound_by_message_id",
    "get_outbound_for_round",
    "get_outbound_message_id",
    "get_outbound_references_chain",
    "get_unconfirmed_outbound",
    "insert_email_message",
    "load_consumed_replies",
    "load_delivery_review_snapshot",
    "load_outbound_snapshot",
    "load_outbound_emails",
    "load_snapshot_attachment",
    "load_thread_messages",
    "mark_reply_consumed",
    "reserve_outbound_snapshot",
    "update_email_message_sent",
    "update_email_message_state",
    "create_operator_resume_resolution",
    "load_operator_resume_resolution",
    "OperatorResolutionSubmission",
    "commit_operator_resume_resolution",
    "operator_resume_dedup_key",
    "prepare_authoritative_operator_resume",
    "clear_reply_context",
    "get_clarification_round",
    "load_clarified_fields",
    "load_pre_clarify_extracted",
    "persist_decision",
    "persist_extracted",
    "persist_reconciliation",
    "replace_line_items",
    "set_alias_candidates",
    "set_clarification_round",
    "set_clarified_fields",
    "set_hours_changes",
    "set_pre_clarify_extracted",
    "update_known_alias",
    "rewind_for_reclaim",
    "AdvanceSendJobOutcome",
    "advance_existing_clarification_delivery_review_job_due_now",
    "advance_existing_send_job_due_now",
    "claim_job",
    "complete_job",
    "count_open_jobs",
    "enqueue_job",
    "fail_job",
    "get_job",
    "get_run_queue_label",
    "release_leases",
    "send_outbound_dedup_key",
    "SettlementOutcome",
    "enqueue_classified_retry",
    "enqueue_operator_resume_retry",
    "settle_pipeline_job",
    "settle_outbound_delivery_job",
    "settle_background_terminal",
    "settle_infrastructure_failure",
    "reap_expired_final_attempt",
    "insert_or_get_inbound_event",
    "load_inbound_event",
    "purge_terminal_inbound_events",
    "load_roster_for_business",
    "_ACCENT_CLASS_MAP",
    "_TERMINAL_STATUSES",
    "RUN_COLS",
    "_scrub",
    "claim_status",
    "create_run",
    "find_business_by_sender",
    "find_run_by_message_id",
    "insert_inbound_email",
    "link_email_to_run",
    "load_business_name",
    "load_inbound_email",
    "load_run",
    "load_source_email",
    "record_run_error",
    "set_status",
]
