"""DB repo package facade -- re-exports the full live attribute surface (public API
plus get_connection, _conn_ctx, _nulltx, _TERMINAL_STATUSES, _ACCENT_CLASS_MAP,
_pad_references, _scrub) so existing callers (`from app.db import repo`,
`import app.db.repo as repo_mod`) and most test monkeypatch seams
(`monkeypatch.setattr(repo, "fn", ...)`) keep working unchanged post-split.
NOTE: a facade-level patch does NOT intercept an internal
same-module call inside one of the aggregate modules (e.g. record_run_error's own
call to set_status/_scrub inside runs.py) -- those two tests patch app.db.repo.runs
directly; see tests/test_gateway.py and tests/test_persistence.py.
"""

from app.db.repo._shared import _conn_ctx, _nulltx
from app.db.repo.demo import (
    bind_demo_business,
    get_demo_binding,
    get_record_only_flag,
    list_businesses,
    load_all_runs,
    load_line_items,
    set_record_only,
)
from app.db.repo.emails import (
    _HEADER_MATCH_PREDICATE,
    _pad_references,
    find_any_run_for_header,
    find_awaiting_reply_for_header,
    find_stranded_unconsumed_replies,
    get_inbound_by_message_id,
    get_outbound_for_round,
    get_outbound_message_id,
    get_outbound_references_chain,
    insert_email_message,
    load_consumed_replies,
    load_outbound_emails,
    load_thread_messages,
    mark_reply_consumed,
    update_email_message_sent,
    update_email_message_state,
)
from app.db.repo.pipeline_state import (
    clear_reply_context,
    get_clarification_round,
    load_clarified_fields,
    load_pre_clarify_extracted,
    persist_decision,
    persist_extracted,
    persist_reconciliation,
    replace_line_items,
    set_alias_candidates,
    set_clarification_round,
    set_clarified_fields,
    set_pre_clarify_extracted,
    update_known_alias,
)
from app.db.repo.roster import load_roster_for_business
from app.db.repo.runs import (
    _ACCENT_CLASS_MAP,
    _TERMINAL_STATUSES,
    RUN_COLS,
    _scrub,
    claim_status,
    create_run,
    find_business_by_sender,
    find_run_by_message_id,
    insert_inbound_email,
    link_email_to_run,
    load_business_name,
    load_inbound_email,
    load_run,
    load_source_email,
    record_run_error,
    set_status,
    sweep_stranded_runs,
)
from app.db.supabase import get_connection

__all__ = [
    "get_connection",
    "_conn_ctx",
    "_nulltx",
    "bind_demo_business",
    "get_demo_binding",
    "list_businesses",
    "load_all_runs",
    "load_line_items",
    "set_record_only",
    "get_record_only_flag",
    "_HEADER_MATCH_PREDICATE",
    "_pad_references",
    "find_any_run_for_header",
    "find_awaiting_reply_for_header",
    "find_stranded_unconsumed_replies",
    "get_inbound_by_message_id",
    "get_outbound_for_round",
    "get_outbound_message_id",
    "get_outbound_references_chain",
    "insert_email_message",
    "load_consumed_replies",
    "load_outbound_emails",
    "load_thread_messages",
    "mark_reply_consumed",
    "update_email_message_sent",
    "update_email_message_state",
    "clear_reply_context",
    "get_clarification_round",
    "load_clarified_fields",
    "load_pre_clarify_extracted",
    "persist_decision",
    "persist_extracted",
    "persist_reconciliation",
    "replace_line_items",
    "set_alias_candidates",
    "set_clarification_round",
    "set_clarified_fields",
    "set_pre_clarify_extracted",
    "update_known_alias",
    "load_roster_for_business",
    "_ACCENT_CLASS_MAP",
    "_TERMINAL_STATUSES",
    "RUN_COLS",
    "_scrub",
    "claim_status",
    "create_run",
    "find_business_by_sender",
    "find_run_by_message_id",
    "insert_inbound_email",
    "link_email_to_run",
    "load_business_name",
    "load_inbound_email",
    "load_run",
    "load_source_email",
    "record_run_error",
    "set_status",
    "sweep_stranded_runs",
]
