"""Generates `docs/ASSERTION-INVENTORY.md` from `tests/assertion_inventory.py`.

`render_view()` builds fully deterministic markdown from `ASSERTION_INVENTORY`
and `FILE_SCOPE_NOTES`: entries are sorted by `(file, line, col_offset)` before
rendering, so regenerating twice in a row produces byte-identical output
(`git status --porcelain docs/ASSERTION-INVENTORY.md` stays empty). Every
count in the output — totals, the presence/absence split, the per-layer and
per-route breakdowns, the per-file table — is DERIVED from the registry at
render time, never hand-pinned here or in the registry itself: the
committed markdown is the human-readable proof that the counts a reviewer
reads are exactly the counts the guard enforces, not a second, driftable copy
of them.

`main()`'s `--check` flag mirrors `eval/run_eval.py`'s regression-gate
contract (`eval/run_eval.py:695` onward): regenerate in memory, compare
against the committed file, and on any mismatch print a unified diff and exit
1 rather than silently passing. Wired into `ci.yml`'s `lint` job as the
"Assertion inventory view is current" step.

Usage:
  uv run python scripts/render_assertion_inventory.py          # write docs/ASSERTION-INVENTORY.md
  uv run python scripts/render_assertion_inventory.py --check  # staleness gate (CI)
"""

from __future__ import annotations

import argparse
import difflib
import pathlib
import sys
from collections import Counter
from collections.abc import Sequence

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "ASSERTION-INVENTORY.md"

# `tests` is deliberately NOT in [tool.setuptools.packages.find]'s include list
# (only `app*` is an installed package — pyproject.toml:36-38), so running this
# script directly (`uv run python scripts/render_assertion_inventory.py`, the
# exact invocation this plan's <verify> uses) puts `scripts/` on sys.path[0],
# not the repo root, and `tests.assertion_inventory` would not be importable.
# pytest sidesteps this via its own rootdir insertion; a directly-run script
# has no such mechanism, so it is inserted explicitly, before the import that
# needs it.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tests.assertion_inventory import (  # noqa: E402 — must follow the sys.path insert above
    ASSERTION_INVENTORY,
    FILE_SCOPE_NOTES,
    AssertionClass,
    AssertionEntry,
)


def _sorted_entries() -> list[AssertionEntry]:
    return sorted(ASSERTION_INVENTORY.values(), key=lambda e: (e.file, e.line, e.col_offset))


def _registry_key(entry: AssertionEntry) -> str:
    return f"{pathlib.Path(entry.file).stem}:{entry.line}:{entry.col_offset}"


def _truncate(text: str, limit: int = 80) -> str:
    flat = text.replace("\n", " ").replace("|", "\\|")
    return flat if len(flat) <= limit else flat[: limit - 3] + "..."


def _render_counts_table(rows: Sequence[tuple[str, int]], headers: tuple[str, str]) -> list[str]:
    out = [f"| {headers[0]} | {headers[1]} |", "|---|---|"]
    out.extend(f"| {label} | {count} |" for label, count in rows)
    return out


def render_view() -> str:
    """Build the full markdown view. Pure function of `ASSERTION_INVENTORY` and
    `FILE_SCOPE_NOTES` — no I/O, no clock, no randomness, so calling it twice
    with an unchanged registry returns an identical string.
    """
    entries = _sorted_entries()
    lines: list[str] = []

    lines.append("# Assertion Inventory (GUARD-01)")
    lines.append("")
    lines.append(
        "Generated by `scripts/render_assertion_inventory.py` from "
        "`tests/assertion_inventory.py`. Do not hand-edit — regenerate with "
        "`uv run python scripts/render_assertion_inventory.py` and commit the "
        "result. `--check` verifies this file is not stale and is wired into "
        "`.github/workflows/ci.yml`'s `lint` job."
    )
    lines.append("")

    # --- Baseline counts (derived output, never hand-pinned) ---
    total = len(entries)
    presence = sum(1 for e in entries if e.assertion_class == AssertionClass.PRESENCE)
    absence = total - presence

    lines.append("## Baseline counts")
    lines.append("")
    lines.append(f"- Total classified `.text` comparisons: **{total}**")
    lines.append(f"- Presence: **{presence}** / Absence: **{absence}**")
    lines.append(f"- Files scoped in `FILE_SCOPE_NOTES`: **{len(FILE_SCOPE_NOTES)}**")
    lines.append("")

    lines.append("### Per-layer breakdown")
    lines.append("")
    layer_counts = Counter(e.layer.value for e in entries)
    lines.extend(
        _render_counts_table(
            sorted(layer_counts.items()),
            ("Layer", "Count"),
        )
    )
    lines.append("")

    lines.append("### Per-route breakdown")
    lines.append("")
    route_counts = Counter(e.route for e in entries)
    lines.extend(
        _render_counts_table(
            [(f"`{route}`", count) for route, count in sorted(route_counts.items())],
            ("Route", "Count"),
        )
    )
    lines.append("")

    # --- Per-file counts ---
    lines.append("## Per-file counts")
    lines.append("")
    lines.append("| File | Total | Presence | Absence |")
    lines.append("|---|---|---|---|")
    file_groups: dict[str, list[AssertionEntry]] = {}
    for entry in entries:
        file_groups.setdefault(entry.file, []).append(entry)
    for file in sorted(file_groups):
        group = file_groups[file]
        p = sum(1 for e in group if e.assertion_class == AssertionClass.PRESENCE)
        a = len(group) - p
        lines.append(f"| `{file}` | {len(group)} | {p} | {a} |")
    lines.append("")

    # --- Full classified listing ---
    lines.append("## Classified assertions")
    lines.append("")
    lines.append("| Key | Route | Class | Layer | Source |")
    lines.append("|---|---|---|---|---|")
    for entry in entries:
        lines.append(
            f"| `{_registry_key(entry)}` | `{entry.route}` | {entry.assertion_class.value} "
            f"| {entry.layer.value} | `{_truncate(entry.source_text)}` |"
        )
    lines.append("")

    # --- Files with zero affected assertions ---
    lines.append("## Files with zero affected assertions")
    lines.append("")
    lines.append(
        "Every file under `tests/` whose text contains the substring `.text` is listed "
        "here with its recorded reason — including files with zero real `.text` "
        "comparisons and files whose comparisons all target a route this milestone does "
        "not convert (`/ops`, `/`, `/health/*`, `/webhook/inbound`, or a non-HTTP body "
        "such as `caplog.text`). Nothing is silently out of scope."
    )
    lines.append("")
    for file in sorted(FILE_SCOPE_NOTES):
        lines.append(f"### `{file}`")
        lines.append("")
        lines.append(FILE_SCOPE_NOTES[file])
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def _check(fresh: str) -> int:
    if not OUTPUT_PATH.exists():
        print(
            f"{OUTPUT_PATH} does not exist. Run without --check first to generate it.",
            file=sys.stderr,
        )
        return 1
    committed = OUTPUT_PATH.read_text(encoding="utf-8")
    if fresh == committed:
        print(f"--check passed: {OUTPUT_PATH.relative_to(REPO_ROOT)} is current")
        return 0
    diff = difflib.unified_diff(
        committed.splitlines(keepends=True),
        fresh.splitlines(keepends=True),
        fromfile=f"{OUTPUT_PATH.relative_to(REPO_ROOT)} (committed)",
        tofile=f"{OUTPUT_PATH.relative_to(REPO_ROOT)} (regenerated)",
    )
    sys.stderr.writelines(diff)
    print(
        f"\nSTALE: {OUTPUT_PATH.relative_to(REPO_ROOT)} does not match "
        "tests/assertion_inventory.py. Regenerate with "
        "`uv run python scripts/render_assertion_inventory.py`.",
        file=sys.stderr,
    )
    return 1


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and diff against the committed file; exit 1 on mismatch",
    )
    args = parser.parse_args(argv)

    fresh = render_view()

    if args.check:
        return _check(fresh)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(fresh, encoding="utf-8")
    print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} written ({len(fresh)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
